<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPcplzcz\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPcplzcz/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerPcplzcz.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerPcplzcz\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerPcplzcz\appProdProjectContainer([
    'container.build_hash' => 'Pcplzcz',
    'container.build_id' => 'ff16c5f3',
    'container.build_time' => 1763828043,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPcplzcz');
