CREATE TABLE ps_category (
    id_category INT AUTO_INCREMENT PRIMARY KEY,
    id_parent INT NOT NULL DEFAULT 0,
    level_depth INT NOT NULL DEFAULT 0,
    position INT NOT NULL DEFAULT 0,
    is_root_category TINYINT(1) NOT NULL DEFAULT 0,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    meta_title VARCHAR(255),
    meta_description VARCHAR(255),
    meta_keywords VARCHAR(255),
    link_rewrite VARCHAR(255),
    active TINYINT(1) NOT NULL DEFAULT 1,
    date_add DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_upd DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE ps_product (
    id_product INT AUTO_INCREMENT PRIMARY KEY,
    id_category_default INT NOT NULL,
    reference VARCHAR(64),
    price DECIMAL(20, 6) NOT NULL DEFAULT 0,
    active TINYINT(1) NOT NULL DEFAULT 1,
    date_add DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_upd DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE ps_customer (
    id_customer INT AUTO_INCREMENT PRIMARY KEY,
    firstname VARCHAR(32) NOT NULL,
    lastname VARCHAR(32) NOT NULL,
    email VARCHAR(128) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    date_add DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_upd DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE ps_orders (
    id_order INT AUTO_INCREMENT PRIMARY KEY,
    id_customer INT NOT NULL,
    total DECIMAL(20, 6) NOT NULL DEFAULT 0,
    date_add DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_upd DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);